name: strassen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - name: Update install
      run: sudo apt update
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.7
      with:
        cmake-version: '3.16.x'
    - name: Install gtest manually
      run: git clone https://github.com/google/googletest.git -b release-1.10.0  && cd googletest && mkdir build && cd build && cmake .. -DBUILD_GMOCK=OFF -DINSTALL_GTEST=ON && sudo make install 
    - name: Install Eigen and TBB
      run: sudo apt-get install libtbb-dev libeigen3-dev
    - uses: actions/checkout@v1
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Make
      run: cd build && make
    - name: Run Test
      run: cd build && ctest --no-compress-output -T Test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.7
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: build/Testing/**/Test.xml
